"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
type Memory={id:string;kind:string;title:string;detail:string;createdAt:string}; type Cat={id:string;displayName:string;description:string;status:string;origin:string;events:number}; type Reply={message:string;clarification?:string}; type LifetimeStats={catsRecorded:number;catsFoundHomes:number;spayedNeutered:number};
const prompts=["The thinner black boy from Jefferson got neutered today, rabies and FVRCP.","Sarah Yunker donated two 12-pound bags of Friskies.","We made $300 selling stickers.","Which cats are waiting for adoption?"];
export default function Home(){
 const [tab,setTab]=useState("home"),[mode,setMode]=useState<"mic"|"text"|"ask"|"photo"|null>(null),[text,setText]=useState(""),[reply,setReply]=useState<Reply|null>(null),[loading,setLoading]=useState(false),[pageLoading,setPageLoading]=useState(false),[listening,setListening]=useState(false),[micError,setMicError]=useState(""),[memories,setMemories]=useState<Memory[]>([]),[cats,setCats]=useState<Cat[]>([]),[stats,setStats]=useState<LifetimeStats>({catsRecorded:0,catsFoundHomes:0,spayedNeutered:0}); const fileRef=useRef<HTMLInputElement>(null),speechRef=useRef<any>(null);
 const refresh=async()=>{try{const r=await fetch("/api/assistant");if(r.ok){const d=await r.json();setMemories(d.memories||[]);setCats(d.cats||[]);setStats(d.stats||{catsRecorded:0,catsFoundHomes:0,spayedNeutered:0})}}catch{}}; useEffect(()=>{refresh()},[]);
 const submit=async()=>{if(!text.trim())return;setLoading(true);setReply(null);try{const r=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:text.trim(),mode})});setReply(await r.json());await refresh()}catch{setReply({message:"I couldn’t save that just now. Your words are still here—please try again."})}finally{setLoading(false)}};
 const open=(next:"text"|"ask"|"photo")=>{setMode(next);setReply(null);setMicError("");setText("");if(next==="photo")fileRef.current?.click()};
 const startMic=()=>{setMode("mic");setReply(null);setText("");setMicError("");const w=window as any;const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setMicError("Live transcription isn’t available in this browser. Use Type an update instead.");return}const recognition=new Recognition();speechRef.current=recognition;recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-US";recognition.onstart=()=>setListening(true);recognition.onresult=(event:any)=>{let words="";for(let i=0;i<event.results.length;i++)words+=event.results[i][0].transcript;setText(words)};recognition.onerror=(event:any)=>{setListening(false);setMicError(event.error==="not-allowed"?"Microphone access was blocked. Allow access or use Type an update.":"I couldn’t hear that clearly. Tap the microphone to try again.")};recognition.onend=()=>setListening(false);recognition.start()};
 const stopMic=()=>{speechRef.current?.stop();setListening(false)};
 const onPhoto=(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files?.[0]){setMode("photo");setText(`Photo added: ${e.target.files[0].name}. Female gray kitten from Jefferson, one of the kittens from the big litter.`)}};
 const switchTab=(next:string)=>{if(next===tab)return;setPageLoading(true);window.setTimeout(()=>{setTab(next);setPageLoading(false)},350)};
 const visible:any[]=tab==="cats"?cats.map(c=>({id:c.id,kind:"cat",title:c.displayName,detail:`${c.description} · ${c.status}`,createdAt:`${c.events} events`})):memories;
 const lifetimeImpact=<section className="summaryCard"><div><p className="eyebrow">LIFETIME IMPACT</p><h3>Your work at a glance</h3></div><div className="stats"><div><strong>{stats.catsRecorded}</strong><span>Cats recorded</span></div><div><strong>{stats.catsFoundHomes}</strong><span>Found homes</span></div><div><strong>{stats.spayedNeutered}</strong><span>Spayed/neutered</span></div></div></section>;
 return <main className="shell"><header className="topbar"><div className="topbarTitle"><p className="eyebrow">GOOD MORNING, ARI</p><h1>TNR Assistant</h1></div><button className="avatar" aria-label="Open profile">A</button></header>
 {tab==="home"?<><section className="hero"><img className="peekCat" src="/tnr-cat-peeking.png" alt="Gray cat peeking over the card"/><div className="colonyBadge"><img src="/cat-colony.png" alt="Cat colony"/></div><div className="heroCopy"><p className="eyebrow light">THE FULL STORY OF YOUR RESCUE WORK.</p><h2>What happened today?</h2><p>Tell me naturally. I’ll organize the details and ask only when I’m unsure.</p></div><div className="recordActions"><button className="talk" onClick={startMic}><span className="mic">●</span><span><strong>Speak an update</strong><small>Open microphone</small></span></button><button className="typeUpdate" onClick={()=>open("text")}><span className="typeIcon">Aa</span><span><strong>Type an update</strong><small>Open text window</small></span></button></div></section><section className="quickGrid"><button onClick={()=>open("photo")}><span className="actionIcon photo">▣</span><span><strong>Add photo</strong><small>Document a cat</small></span><b>›</b></button><button onClick={()=>open("ask")}><span className="actionIcon ask">?</span><span><strong>Ask your assistant</strong><small>Find anything</small></span><b>›</b></button></section><section className="comingSoon"><p className="eyebrow">COMING SOON</p><div className="comingSoonGrid"><button disabled><span>f</span>Generate Facebook post</button><button disabled><span>♪</span>Generate TikTok video</button><button disabled><span>◎</span>Generate Instagram post</button></div></section></>:tab==="dashboard"?<><section className="dashboardIntro"><p className="eyebrow">DASHBOARD</p><h2>Your rescue impact</h2><p>See the difference your work is making.</p></section>{lifetimeImpact}<section className="comingSoon dashboardActions"><p className="eyebrow">COMING SOON</p><div className="comingSoonGrid reports"><button disabled><span>▤</span>Operations report</button><button disabled><span>↗</span>Sharable rescue report</button></div></section></>:<><section className="pageIntro"><p className="eyebrow">RESCUE MEMORY</p><h2>{tab==="cats"?"Every cat, remembered":"The full timeline"}</h2><p>{tab==="cats"?"Names are optional. Context is the identity.":"Original words and structured updates stay together."}</p></section><section className="recent"><div className="sectionTitle"><div><p className="eyebrow">RECORDED</p><h3>{tab==="cats"?"Cats":"All activity"}</h3></div></div><div className="memoryList">{visible.slice(0,30).map(item=><article key={item.id}><span className={`eventIcon ${item.kind==="income"||item.kind==="in-kind"?"green":item.kind==="expense"?"coral":"blue"}`}>{item.kind==="cat"?"♧":item.kind==="income"?"↗":item.kind==="expense"?"↘":"✦"}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.createdAt}</time></article>)}{!visible.length&&<div className="empty">Your first memory will appear here.</div>}</div></section></>}
 <input ref={fileRef} type="file" accept="image/*" capture="environment" hidden onChange={onPhoto}/>{mode&&<div className="sheetBackdrop" onClick={()=>{stopMic();setMode(null)}}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="handle"/><p className="eyebrow">{mode==="ask"?"ASK YOUR ASSISTANT":mode==="photo"?"PHOTO + CONTEXT":mode==="mic"?(listening?"MICROPHONE IS ON":"MICROPHONE PAUSED"):"TYPE AN UPDATE"}</p><h2>{mode==="ask"?"What do you want to know?":mode==="photo"?"Tell me about this cat":mode==="mic"?(listening?"I’m listening…":"Review what I heard"):"Tell me what happened"}</h2>{mode==="mic"?<div className="voiceCapture"><button className={`bigMic ${listening?"isListening":""}`} onClick={listening?stopMic:startMic} aria-label={listening?"Stop microphone":"Start microphone"}>{listening?"■":"●"}</button><p>{text||"Start speaking—your words will appear here."}</p>{micError&&<div className="micError">{micError}</div>}</div>:<textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Type naturally…"/>}<div className="suggestions">{prompts.slice(1).map(p=><button key={p} onClick={()=>setText(p)}>{p}</button>)}</div>{reply&&<div className={`reply ${reply.clarification?"clarify":""}`}><strong>{reply.clarification?"One quick question":"Recorded"}</strong><p>{reply.message}</p>{reply.clarification&&<button onClick={()=>{setText(reply.clarification!);setReply(null)}}>{reply.clarification}</button>}</div>}<button className="primary" disabled={loading||!text.trim()} onClick={()=>{stopMic();submit()}}>{loading?"Checking the rescue memory…":mode==="ask"?"Ask":"Review & record"}</button><button className="close" onClick={()=>{stopMic();setMode(null)}}>Close</button></section></div>}
 {(loading||pageLoading)&&<div className="loadingOverlay" role="status" aria-live="polite"><img src="/tnr-cat.png" alt=""/><span>{loading?"Your assistant is working…":"Loading…"}</span></div>}<nav>{[["home","⌂","Home"],["cats","♧","Cats"],["activity","◎","Activity"],["dashboard","▥","Dashboard"]].map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>switchTab(id)}><span>{icon}</span>{label}</button>)}</nav></main>}
