"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
type Memory={id:string;kind:string;title:string;detail:string;createdAt:string}; type Cat={id:string;displayName:string;description:string;status:string;origin:string;events:number}; type Reply={message:string;clarification?:string};
const prompts=["The thinner black boy from Jefferson got neutered today, rabies and FVRCP.","Sarah Yunker donated two 12-pound bags of Friskies.","We made $300 selling stickers.","Which cats are waiting for adoption?"];
export default function Home(){
 const [tab,setTab]=useState("home"),[mode,setMode]=useState<"talk"|"ask"|"photo"|null>(null),[text,setText]=useState(""),[reply,setReply]=useState<Reply|null>(null),[loading,setLoading]=useState(false),[memories,setMemories]=useState<Memory[]>([]),[cats,setCats]=useState<Cat[]>([]); const fileRef=useRef<HTMLInputElement>(null);
 const refresh=async()=>{try{const r=await fetch("/api/assistant");if(r.ok){const d=await r.json();setMemories(d.memories||[]);setCats(d.cats||[])}}catch{}}; useEffect(()=>{refresh()},[]);
 const submit=async()=>{if(!text.trim())return;setLoading(true);setReply(null);try{const r=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:text.trim(),mode})});setReply(await r.json());await refresh()}catch{setReply({message:"I couldn’t save that just now. Your words are still here—please try again."})}finally{setLoading(false)}};
 const open=(next:"talk"|"ask"|"photo")=>{setMode(next);setReply(null);setText(next==="talk"?prompts[0]:"");if(next==="photo")fileRef.current?.click()};
 const onPhoto=(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files?.[0]){setMode("photo");setText(`Photo added: ${e.target.files[0].name}. Female gray kitten from Jefferson, one of the kittens from the big litter.`)}};
 const visible:any[]=tab==="cats"?cats.map(c=>({id:c.id,kind:"cat",title:c.displayName,detail:`${c.description} · ${c.status}`,createdAt:`${c.events} events`})):memories;
 return <main className="shell"><header className="topbar"><div className="brandMark">R</div><div><p className="eyebrow">GOOD MORNING, ARI</p><h1>Rescue Assistant</h1></div><button className="avatar" aria-label="Open profile">A</button></header>
 {tab==="home"?<><section className="hero"><p className="eyebrow light">YOUR RESCUE, REMEMBERED</p><h2>What happened today?</h2><p>Tell me naturally. I’ll organize the details and ask only when I’m unsure.</p><button className="talk" onClick={()=>open("talk")}><span className="mic">●</span><span><strong>Talk to the rescue</strong><small>Tap and speak naturally</small></span><span className="waves">ıııı</span></button></section><section className="quickGrid"><button onClick={()=>open("photo")}><span className="actionIcon photo">▣</span><span><strong>Add photo</strong><small>Document a cat</small></span><b>›</b></button><button onClick={()=>open("ask")}><span className="actionIcon ask">?</span><span><strong>Ask the rescue</strong><small>Find anything</small></span><b>›</b></button></section><section className="summaryCard"><div><p className="eyebrow">RIGHT NOW</p><h3>Your rescue at a glance</h3></div><div className="stats"><div><strong>{cats.filter(c=>!["adopted","returned to colony"].includes(c.status)).length}</strong><span>In care</span></div><div><strong>{cats.filter(c=>["awaiting vet","recovering"].includes(c.status)).length}</strong><span>Need attention</span></div><div><strong>{cats.filter(c=>c.status==="available for adoption").length}</strong><span>Ready for homes</span></div></div></section></>:<section className="pageIntro"><p className="eyebrow">RESCUE MEMORY</p><h2>{tab==="cats"?"Every cat, remembered":tab==="activity"?"The full timeline":"Money & resources"}</h2><p>{tab==="cats"?"Names are optional. Context is the identity.":tab==="activity"?"Original words and structured updates stay together.":"Operational visibility—not formal accounting."}</p></section>}
 <section className="recent"><div className="sectionTitle"><div><p className="eyebrow">{tab==="home"?"RECENT MEMORY":"RECORDED"}</p><h3>{tab==="home"?"What I’ve recorded":tab==="resources"?"Resource flow":tab==="cats"?"Cats":"All activity"}</h3></div>{tab==="home"&&<button onClick={()=>setTab("activity")}>See all</button>}</div><div className="memoryList">{visible.filter(x=>tab!=="resources"||["income","expense","in-kind"].includes(x.kind)).slice(0,tab==="home"?4:30).map(item=><article key={item.id}><span className={`eventIcon ${item.kind==="income"||item.kind==="in-kind"?"green":item.kind==="expense"?"coral":"blue"}`}>{item.kind==="cat"?"♧":item.kind==="income"?"↗":item.kind==="expense"?"↘":"✦"}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.createdAt}</time></article>)}{!visible.length&&<div className="empty">Your first memory will appear here.</div>}</div></section>
 <input ref={fileRef} type="file" accept="image/*" capture="environment" hidden onChange={onPhoto}/>{mode&&<div className="sheetBackdrop" onClick={()=>setMode(null)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="handle"/><p className="eyebrow">{mode==="ask"?"ASK THE RESCUE":mode==="photo"?"PHOTO + CONTEXT":"I’M LISTENING"}</p><h2>{mode==="ask"?"What do you want to know?":mode==="photo"?"Tell me about this cat":"Tell me what happened"}</h2><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Speak or type naturally…"/><div className="suggestions">{prompts.slice(1).map(p=><button key={p} onClick={()=>setText(p)}>{p}</button>)}</div>{reply&&<div className={`reply ${reply.clarification?"clarify":""}`}><strong>{reply.clarification?"One quick question":"Recorded"}</strong><p>{reply.message}</p>{reply.clarification&&<button onClick={()=>{setText(reply.clarification!);setReply(null)}}>{reply.clarification}</button>}</div>}<button className="primary" disabled={loading} onClick={submit}>{loading?"Checking the rescue memory…":mode==="ask"?"Ask":"Review & record"}</button><button className="close" onClick={()=>setMode(null)}>Close</button></section></div>}
 <nav>{[["home","⌂","Home"],["cats","♧","Cats"],["activity","◎","Activity"],["resources","◌","Resources"]].map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</nav></main>}
