import { env } from "cloudflare:workers";
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}-${crypto.randomUUID()}`;
async function ready(){const db=env.DB;const sql=[
"CREATE TABLE IF NOT EXISTS colonies (id TEXT PRIMARY KEY, name TEXT NOT NULL, general_location TEXT, notes TEXT, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS cats (id TEXT PRIMARY KEY, name TEXT, sex TEXT, age_class TEXT, appearance TEXT, distinguishing_characteristics TEXT, health_observations TEXT, reproductive_significance TEXT, origin_colony_id TEXT, current_status TEXT NOT NULL DEFAULT 'observed', current_location TEXT, microchip_number TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS people (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT, general_location TEXT, contact TEXT, created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS ai_inputs (id TEXT PRIMARY KEY, transcription TEXT NOT NULL, input_type TEXT NOT NULL, interpretation TEXT, confidence REAL, clarification TEXT, correction TEXT, created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, cat_id TEXT, event_type TEXT NOT NULL, occurred_at TEXT NOT NULL, location TEXT, person_id TEXT, notes TEXT, source_input_id TEXT, created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY, transaction_type TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('inflow','outflow')), date TEXT NOT NULL, amount REAL, currency TEXT DEFAULT 'USD', person_id TEXT, category TEXT, description TEXT NOT NULL, item TEXT, quantity REAL, unit TEXT, estimated_value REAL, related_cat_id TEXT, related_event_id TEXT, related_colony_id TEXT, source_input_id TEXT, created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS photos (id TEXT PRIMARY KEY, cat_id TEXT, event_id TEXT, storage_location TEXT NOT NULL, taken_at TEXT NOT NULL, caption TEXT)",
"CREATE INDEX IF NOT EXISTS idx_events_cat_date ON events(cat_id, occurred_at)","CREATE INDEX IF NOT EXISTS idx_cats_origin_status ON cats(origin_colony_id, current_status)","CREATE INDEX IF NOT EXISTS idx_transactions_direction_date ON transactions(direction, date)" ]; await db.batch(sql.map(s=>db.prepare(s)));
 const count=await db.prepare("SELECT COUNT(*) AS n FROM cats").first<{n:number}>(); if(!count?.n){const t=now();await db.batch([db.prepare("INSERT OR IGNORE INTO colonies VALUES(?,?,?,?,?,?)").bind("col-jefferson","Jefferson","Jefferson neighborhood",null,"active",t),db.prepare("INSERT INTO cats(id,name,sex,age_class,appearance,distinguishing_characteristics,health_observations,origin_colony_id,current_status,current_location,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind("cat-thin-black",null,"male","kitten","black","noticeably thinner than his brother","recovering from illness","col-jefferson","awaiting vet","Ari's care",t,t),db.prepare("INSERT INTO cats(id,name,sex,age_class,appearance,distinguishing_characteristics,health_observations,origin_colony_id,current_status,current_location,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind("cat-black-brother",null,"male","kitten","black","larger brother","appears healthy","col-jefferson","available for adoption","foster",t,t),db.prepare("INSERT INTO cats(id,name,sex,age_class,appearance,distinguishing_characteristics,origin_colony_id,current_status,current_location,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind("cat-pepper","Pepper","female","adult","tortoiseshell","amber patch over left eye","col-jefferson","available for adoption","foster",t,t)])}}
function display(c:any){return c.name||[c.distinguishing_characteristics,c.appearance,c.sex,c.age_class].filter(Boolean).join(" ")}
export async function GET(){await ready();const db=env.DB;const cs=await db.prepare("SELECT c.*,co.name origin,(SELECT COUNT(*) FROM events e WHERE e.cat_id=c.id) events FROM cats c LEFT JOIN colonies co ON co.id=c.origin_colony_id ORDER BY c.updated_at DESC").all();const ms=await db.prepare("SELECT id,event_type kind,COALESCE((SELECT COALESCE(name, distinguishing_characteristics||' '||appearance) FROM cats WHERE id=cat_id), event_type) title,notes detail,occurred_at createdAt FROM events UNION ALL SELECT id,CASE WHEN transaction_type='in_kind_donation' THEN 'in-kind' WHEN direction='inflow' THEN 'income' ELSE 'expense' END,description,CASE WHEN amount IS NOT NULL THEN '$'||printf('%.2f',amount)||' · '||COALESCE(category,'') ELSE COALESCE(CAST(quantity AS TEXT)||' '||unit||' · '||item,'Resource') END,date FROM transactions ORDER BY createdAt DESC LIMIT 30").all();return Response.json({cats:cs.results.map((c:any)=>({id:c.id,displayName:display(c),description:[c.appearance,c.sex,c.age_class,c.origin].filter(Boolean).join(" · "),status:c.current_status,origin:c.origin,events:c.events})),memories:ms.results})}
export async function POST(req:Request){await ready();const {input,mode}=await req.json() as {input?:string;mode?:string};if(!input?.trim())return Response.json({message:"Tell me what happened first."},{status:400});const s=input.trim(),l=s.toLowerCase(),db=env.DB,inputId=id("input"),t=now();let interpretation="unknown",confidence=.55,clarification:string|null=null,message="I saved your original words, but I need one more detail before changing a record.";
 if(/which cats|waiting for adoption|ready for adoption/.test(l)){const r=await db.prepare("SELECT name,distinguishing_characteristics,appearance FROM cats WHERE current_status='available for adoption'").all();message=r.results.length?`${r.results.length} cats are ready for adoption: ${r.results.map((c:any)=>display(c)).join(", ")}.`:"No cats are currently marked ready for adoption.";interpretation="query: adoption status";confidence=.98}
 else if(/income and expenses|income versus expenses/.test(l)){const r=await db.prepare("SELECT direction,SUM(amount) total FROM transactions WHERE amount IS NOT NULL GROUP BY direction").all();const v=Object.fromEntries(r.results.map((x:any)=>[x.direction,x.total]));message=`Recorded cash in: $${Number(v.inflow||0).toFixed(2)}. Recorded cash out: $${Number(v.outflow||0).toFixed(2)}.`;interpretation="query: financial summary";confidence=.98}
 else if(/donated/.test(l)&&/(bag|food|friskies|litter)/.test(l)){const qty=Number(l.match(/(\d+)\s*(?:-| )?(?:\d+[- ]?pound )?bags?/)?.[1]||2),person=s.match(/^([A-Z][a-z]+(?:\s+[A-Z][a-z]+)?) donated/)?.[1]||"Unknown donor",pid=id("person");await db.batch([db.prepare("INSERT INTO people VALUES(?,?,?,?,?,?)").bind(pid,person,"donor",null,null,t),db.prepare("INSERT INTO transactions(id,transaction_type,direction,date,person_id,category,description,item,quantity,unit,source_input_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(id("txn"),"in_kind_donation","inflow",t,pid,"food",`${person} donated Friskies`,"Friskies",qty,"12-lb bag",inputId,t)]);message=`Recorded ${qty} 12-pound bags of Friskies from ${person}. No dollar value required.`;interpretation="in-kind donation";confidence=.97}
 else if(/\$\d+/.test(l)&&(l.includes("made")||l.includes("spent")||l.includes("donat"))){const amount=Number(l.match(/\$(\d+(?:\.\d+)?)/)?.[1]),out=l.includes("spent"),desc=l.includes("sticker")?(out?"Brand stickers":"Sticker sales"):s;await db.prepare("INSERT INTO transactions(id,transaction_type,direction,date,amount,currency,category,description,source_input_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id("txn"),out?"operating_expense":"income",out?"outflow":"inflow",t,amount,"USD",l.includes("sticker")?(out?"marketing":"merchandise sales"):"other",desc,inputId,t).run();message=`Recorded $${amount.toFixed(2)} as ${out?"an expense":"income"}: ${desc}.`;interpretation=out?"cash outflow":"cash inflow";confidence=.96}
 else if(/black kitten got adopted|black cat got adopted/.test(l)){clarification="The thinner black boy from Jefferson got adopted.";message="I found two black male kittens from Jefferson. Do you mean the thinner one who has been sick, or his larger brother?";interpretation="adoption; ambiguous cat identity";confidence=.48}
 else if(/thin|thinner/.test(l)&&/black/.test(l)){const cat="cat-thin-black",types=[l.includes("neuter")?"neuter":null,l.includes("rabies")?"vaccination: rabies":null,l.includes("fvrcp")?"vaccination: FVRCP":null].filter(Boolean) as string[];if(!types.length)types.push("observation");await db.batch(types.map(type=>db.prepare("INSERT INTO events(id,cat_id,event_type,occurred_at,notes,source_input_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id("event"),cat,type,t,s,inputId,t)));await db.prepare("UPDATE cats SET current_status=?,updated_at=? WHERE id=?").bind(l.includes("neuter")?"recovering":"awaiting vet",t,cat).run();message=`Matched the thinner black boy from Jefferson. Recorded ${types.join(", ")} and preserved your original words.`;interpretation=`events: ${types.join(", ")}`;confidence=.99}
 else if(/female gray kitten/.test(l)){const cat=id("cat");await db.prepare("INSERT INTO cats(id,sex,age_class,appearance,distinguishing_characteristics,origin_colony_id,current_status,current_location,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(cat,"female","kitten","gray","one of the kittens from the big litter","col-jefferson","observed","unknown",t,t).run();await db.prepare("INSERT INTO events(id,cat_id,event_type,occurred_at,notes,source_input_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id("event"),cat,"intake",t,s,inputId,t).run();message="Created an unnamed female gray kitten from Jefferson and added the big-litter detail to her history.";interpretation="new cat + intake";confidence=.94}
 else if(/pepper.*adopt/.test(l)){await db.prepare("UPDATE cats SET current_status='adopted',updated_at=? WHERE id='cat-pepper'").bind(t).run();await db.prepare("INSERT INTO events(id,cat_id,event_type,occurred_at,notes,source_input_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id("event"),"cat-pepper","adoption",t,s,inputId,t).run();message="Recorded Pepper’s adoption and updated her status to adopted.";interpretation="adoption";confidence=.98}
 await db.prepare("INSERT INTO ai_inputs(id,transcription,input_type,interpretation,confidence,clarification,created_at) VALUES(?,?,?,?,?,?,?)").bind(inputId,s,mode||"text",interpretation,confidence,clarification,t).run();return Response.json({message,clarification})}
