import { index, sqliteTable, text, real, integer, primaryKey } from "drizzle-orm/sqlite-core";
export const colonies=sqliteTable("colonies",{id:text("id").primaryKey(),ownerId:text("owner_id"),name:text("name").notNull(),generalLocation:text("general_location"),notes:text("notes"),status:text("status").notNull().default("active"),createdAt:text("created_at").notNull()});
export const cats=sqliteTable("cats",{version:integer("version").notNull().default(0),id:text("id").primaryKey(),ownerId:text("owner_id"),name:text("name"),sex:text("sex"),ageClass:text("age_class"),appearance:text("appearance"),distinguishingCharacteristics:text("distinguishing_characteristics"),healthObservations:text("health_observations"),reproductiveSignificance:text("reproductive_significance"),originColonyId:text("origin_colony_id").references(()=>colonies.id),currentStatus:text("current_status").notNull().default("observed"),currentLocation:text("current_location"),microchipNumber:text("microchip_number"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},t=>[index("idx_cats_owner_status").on(t.ownerId,t.currentStatus)]);
export const people=sqliteTable("people",{version:integer("version").notNull().default(0),id:text("id").primaryKey(),ownerId:text("owner_id"),name:text("name").notNull(),type:text("type"),generalLocation:text("general_location"),contact:text("contact"),createdAt:text("created_at").notNull()});
export const inputs=sqliteTable("ai_inputs",{id:text("id").primaryKey(),ownerId:text("owner_id"),transcription:text("transcription").notNull(),inputType:text("input_type").notNull(),interpretation:text("interpretation"),confidence:real("confidence"),clarification:text("clarification"),correction:text("correction"),recordsCreated:text("records_created"),recordsUpdated:text("records_updated"),createdAt:text("created_at").notNull()});
export const events=sqliteTable("events",{version:integer("version").notNull().default(0),id:text("id").primaryKey(),ownerId:text("owner_id"),catId:text("cat_id").references(()=>cats.id),eventType:text("event_type").notNull(),occurredAt:text("occurred_at").notNull(),location:text("location"),personId:text("person_id").references(()=>people.id),notes:text("notes"),sourceInputId:text("source_input_id").references(()=>inputs.id),createdAt:text("created_at").notNull()},t=>[index("idx_events_owner_cat_date").on(t.ownerId,t.catId,t.occurredAt)]);
export const photos=sqliteTable("photos",{id:text("id").primaryKey(),ownerId:text("owner_id"),catId:text("cat_id").references(()=>cats.id),eventId:text("event_id").references(()=>events.id),storageLocation:text("storage_location").notNull(),takenAt:text("taken_at").notNull(),caption:text("caption")});
export const transactions=sqliteTable("transactions",{version:integer("version").notNull().default(0),id:text("id").primaryKey(),ownerId:text("owner_id"),transactionType:text("transaction_type").notNull(),direction:text("direction").notNull(),date:text("date").notNull(),amount:real("amount"),currency:text("currency").default("USD"),personId:text("person_id").references(()=>people.id),category:text("category"),description:text("description").notNull(),item:text("item"),quantity:real("quantity"),unit:text("unit"),estimatedValue:real("estimated_value"),relatedCatId:text("related_cat_id").references(()=>cats.id),relatedEventId:text("related_event_id").references(()=>events.id),relatedColonyId:text("related_colony_id").references(()=>colonies.id),sourceInputId:text("source_input_id").references(()=>inputs.id),createdAt:text("created_at").notNull()},t=>[index("idx_transactions_owner_direction_date").on(t.ownerId,t.direction,t.date)]);

// Durable retry receipts and the rescue-wide optimistic concurrency token.
export const writeRequests=sqliteTable("write_requests",{ownerId:text("owner_id").notNull(),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),response:text("response").notNull(),createdAt:text("created_at").notNull()},t=>[primaryKey({columns:[t.ownerId,t.requestKey]})]);
export const rescueRevisions=sqliteTable("rescue_revisions",{ownerId:text("owner_id").primaryKey(),version:integer("version").notNull().default(0)});
export const writeGuards=sqliteTable("write_guards",{ownerId:text("owner_id").primaryKey(),expectedVersion:integer("expected_version").notNull()});
